### ISSUE TITLE
Use rikudou/iban

### ISSUE THREAD

**Issue by RikudouSage** [hubipe/QrPaymentHU#1]
Instead of the bundled implementation, you could use the decoupled [rikudou/iban](https://packagist.org/packages/rikudou/iban) and optionally provide an implementation of the interface for some local format.

Also you may move your Hungarian adapter from this package to the rikudou/iban package to make it available even in contexts outside QR payments.

**Comment by hubipe** [comment]
Thanks, I've decoupled the IBAN interface (https://github.com/hubipe/QrPaymentHU/commit/f792d273c846088cd6f6cb70ef6d06450f9c46a3).

Concerning the Hungarian adapter, I have it prepared, but have to write some tests firsts (hopefully will pull-request it by end of the week).

**Comment by hubipe** [comment]
Bundled implementation of the Hungarian IBAN adapter and  validator successfully moved to rikudou/IBAN, thus closing the issue.
